#!/bin/bash

action=$1
shift

function usage {
  echo "  Customized repeat:"
  echo "    repeat ITEM "
  echo "      mark an item complete then re-enter it"
  echo "    repeat ITEM DAYS"
  echo "      mark an item as complete then re-enter it with a date DAYS from now"
  echo "    repeat ITEM +DAYS"
  echo "      mark an item with a date as complete then re-enter it with a date DAYS from the due date"
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

[ "$action" = "repeat" ] && {
  python $TODO_ACTIONS_DIR/repeat.py "$TODO_FULL_SH" "$TODO_FILE" $@
}